language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libyajl-dev libxml2-dev libxqilla-dev
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qqy gcc-4.9; fi
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9" CC="gcc-4.9"; fi
script:
  - make CC=$CC zedc
  - make test
